site_name: Python Style Documents
pages:
  - Home: index.md
  - Style Guides:
    - Sources: style-guides/source-code-style-guides.md
    - Consensuses: style-guides/consensuses.md
    - Git Flow: style-guides/git-flow.md
    - Git Commit: style-guides/git-commit.md
    - Design Patterns: style-guides/design-patterns.md
  - MileStones: milestones.md
theme: mkdocs
